[package]
name = "scwr"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "scwr"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

scwr_integrity = { workspace = true } 
